# Generated by Django 3.0.5 on 2024-08-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='profile_pic',
        ),
    ]
